"""003_operacoes

Revision ID: 01483d00b08c
Revises: 6bd30b43f000
Create Date: 2026-06-16 13:36:52.189998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01483d00b08c'
down_revision: Union[str, Sequence[str], None] = '6bd30b43f000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_corporativos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('SPLIT', 'GRUPAMENTO', 'BONIFICACAO', 'SUBSCRICAO', 'AMORTIZACAO', 'INCORPORACAO', 'FUSAO', 'CISAO', name='tipo_evento_corporativo_enum'), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('fator', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('valor', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ativo_destino_id', sa.UUID(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('processado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ativo_destino_id'], ['ativos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_corporativos_ativo_id'), 'eventos_corporativos', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_eventos_corporativos_data_evento'), 'eventos_corporativos', ['data_evento'], unique=False)
    op.create_index(op.f('ix_eventos_corporativos_tipo'), 'eventos_corporativos', ['tipo'], unique=False)
    op.create_table('proventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('DIVIDENDO', 'JCP', 'RENDIMENTO', 'AMORTIZACAO', name='tipo_provento_enum'), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ir_retido', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('data_com', sa.Date(), nullable=False),
    sa.Column('data_ex', sa.Date(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('quantidade_na_data', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('reinvestido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proventos_ativo_id'), 'proventos', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_proventos_tipo'), 'proventos', ['tipo'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carteira_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('COMPRA', 'VENDA', name='tipo_movimentacao_enum'), nullable=False),
    sa.Column('tipo_operacao', sa.Enum('SWING', 'DAY_TRADE', 'POSITION', name='tipo_operacao_enum'), nullable=False),
    sa.Column('data_operacao', sa.Date(), nullable=False),
    sa.Column('data_liquidacao', sa.Date(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('corretagem', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('emolumentos', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('iss', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('outras_taxas', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_ativo_id'), 'movimentacoes', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_carteira_id'), 'movimentacoes', ['carteira_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_conta_id'), 'movimentacoes', ['conta_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_data_operacao'), 'movimentacoes', ['data_operacao'], unique=False)
    op.create_index(op.f('ix_movimentacoes_tipo'), 'movimentacoes', ['tipo'], unique=False)
    op.create_index(op.f('ix_movimentacoes_tipo_operacao'), 'movimentacoes', ['tipo_operacao'], unique=False)
    op.create_table('posicoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('carteira_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('preco_medio', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('custo_total', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('custo_total >= 0', name='ck_posicoes_custo_total_nonneg'),
    sa.CheckConstraint('quantidade >= 0', name='ck_posicoes_quantidade_nonneg'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carteira_id', 'ativo_id', 'conta_id', name='uq_posicoes_carteira_ativo_conta')
    )
    op.create_index(op.f('ix_posicoes_ativo_id'), 'posicoes', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_posicoes_carteira_id'), 'posicoes', ['carteira_id'], unique=False)
    op.create_index(op.f('ix_posicoes_conta_id'), 'posicoes', ['conta_id'], unique=False)
    op.create_table('aportes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carteira_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('EXTERNO', 'REINVESTIMENTO', name='tipo_aporte_enum'), nullable=False),
    sa.Column('origem', sa.Enum('DIVIDENDO', 'JCP', 'RENDIMENTO', 'JUROS_RF', 'GANHO_CAPITAL', 'OUTRO', name='origem_aporte_enum'), nullable=True),
    sa.Column('valor', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('data_aporte', sa.Date(), nullable=False),
    sa.Column('movimentacao_id', sa.UUID(), nullable=True),
    sa.Column('provento_id', sa.UUID(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provento_id'], ['proventos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aportes_carteira_id'), 'aportes', ['carteira_id'], unique=False)
    op.create_index(op.f('ix_aportes_conta_id'), 'aportes', ['conta_id'], unique=False)
    op.create_index(op.f('ix_aportes_data_aporte'), 'aportes', ['data_aporte'], unique=False)
    op.create_index(op.f('ix_aportes_tipo'), 'aportes', ['tipo'], unique=False)
    op.drop_constraint(op.f('carteiras_usuario_id_fkey'), 'carteiras', type_='foreignkey')
    op.drop_column('carteiras', 'usuario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carteiras', sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('carteiras_usuario_id_fkey'), 'carteiras', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_aportes_tipo'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_data_aporte'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_conta_id'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_carteira_id'), table_name='aportes')
    op.drop_table('aportes')
    op.drop_index(op.f('ix_posicoes_conta_id'), table_name='posicoes')
    op.drop_index(op.f('ix_posicoes_carteira_id'), table_name='posicoes')
    op.drop_index(op.f('ix_posicoes_ativo_id'), table_name='posicoes')
    op.drop_table('posicoes')
    op.drop_index(op.f('ix_movimentacoes_tipo_operacao'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_tipo'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_data_operacao'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_conta_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_carteira_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_ativo_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_proventos_tipo'), table_name='proventos')
    op.drop_index(op.f('ix_proventos_ativo_id'), table_name='proventos')
    op.drop_table('proventos')
    op.drop_index(op.f('ix_eventos_corporativos_tipo'), table_name='eventos_corporativos')
    op.drop_index(op.f('ix_eventos_corporativos_data_evento'), table_name='eventos_corporativos')
    op.drop_index(op.f('ix_eventos_corporativos_ativo_id'), table_name='eventos_corporativos')
    op.drop_table('eventos_corporativos')
    # ### end Alembic commands ###
