"""Adiciona conta_id a proventos e ajusta observacoes

Revision ID: 05627d7718c5
Revises: 7acfddb0475a
Create Date: 2026-06-28 12:17:42.338325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text # Importar text para executar SQL bruto

# revision identifiers, used by Alembic.
revision: str = '05627d7718c5'
down_revision: Union[str, None] = '7acfddb0475a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adiciona a coluna conta_id como nullable=True inicialmente
    op.add_column('proventos', sa.Column('conta_id', postgresql.UUID(as_uuid=True), nullable=True))
    # Cria o ForeignKeyConstraint
    op.create_foreign_key(
        op.f('fk_proventos_conta_id_contas'),
        'proventos', 'contas',
        ['conta_id'], ['id']
    )

    # Ajusta a coluna 'observacoes' para TEXT e nullable=True
    op.alter_column('proventos', 'observacoes',
               existing_type=sa.VARCHAR(), # Ou sa.Text() se já era TEXT
               type_=sa.Text(),
               existing_nullable=True, # Manter como True se já era nullable
               nullable=True) # Manter como True

    # Ajusta a coluna 'tipo' para usar o ENUM correto
    op.alter_column('proventos', 'tipo',
               existing_type=postgresql.ENUM('DIVIDENDO', 'JCP', 'RENDIMENTO', 'AMORTIZACAO', 'OUTRO', name='tipo_provento_enum'),
               type_=postgresql.ENUM('DIVIDENDO', 'JCP', 'RENDIMENTO', 'AMORTIZACAO', 'OUTRO', name='tipo_provento_enum'),
               existing_nullable=False,
               nullable=False,
               postgresql_using="tipo::tipo_provento_enum") # Garante a conversão de tipo

    # Remove a alteração de nullable=False para conta_id daqui.
    # Isso será feito em uma migração posterior, após preencher os dados.
    # op.alter_column('proventos', 'conta_id',
    #            existing_type=postgresql.UUID(as_uuid=True),
    #            nullable=False,
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverte a alteração de nullable para conta_id (se tivesse sido aplicada)
    # op.alter_column('proventos', 'conta_id',
    #            existing_type=postgresql.UUID(as_uuid=True),
    #            nullable=True,
    #            existing_nullable=False)

    op.drop_constraint(op.f('fk_proventos_conta_id_contas'), 'proventos', type_='foreignkey')
    op.drop_column('proventos', 'conta_id')

    op.alter_column('proventos', 'observacoes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               nullable=True)

    op.alter_column('proventos', 'tipo',
               existing_type=postgresql.ENUM('DIVIDENDO', 'JCP', 'RENDIMENTO', 'AMORTIZACAO', 'OUTRO', name='tipo_provento_enum'),
               type_=postgresql.ENUM('DIVIDENDO', 'JCP', 'RENDIMENTO', 'AMORTIZACAO', 'OUTRO', name='tipo_provento_enum'),
               existing_nullable=False,
               nullable=False,
               postgresql_using="tipo::tipo_provento_enum")
    # ### end Alembic commands ###