"""001_tabelas_iniciais

Revision ID: 0763ac146cd7
Revises: 
Create Date: 2026-06-16 12:44:14.131352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0763ac146cd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('classe', sa.Enum('ACAO', 'FII', 'ETF', 'BDR', 'REIT', 'STOCK', 'CRIPTO', 'FUNDO', 'OUTRO', name='classe_ativo_enum'), nullable=False),
    sa.Column('setor', sa.String(length=255), nullable=True),
    sa.Column('segmento_fii', sa.Enum('TIJOLO', 'PAPEL', 'LOGISTICO', 'SHOPPING', 'LAJES_CORPORATIVAS', 'HIBRIDO', 'RECEBIVEL', 'FUNDO_DE_FUNDOS', 'OUTRO', name='segmento_fii_enum'), nullable=True),
    sa.Column('pais', sa.String(length=10), nullable=False),
    sa.Column('regiao', sa.Enum('BRASIL', 'AMERICA_NORTE', 'EUROPA', 'ASIA', 'OUTRO', name='regiao_enum'), nullable=False),
    sa.Column('moeda', sa.Enum('BRL', 'USD', 'EUR', name='moeda_ativo_enum'), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status_ativo_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('instituicoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('CORRETORA', 'BANCO', 'OUTRO', name='tipo_instituicao_enum'), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status_instituicao_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instituicao_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('CORRENTE', 'INVESTIMENTO', 'POUPANCA', name='tipo_conta_enum'), nullable=False),
    sa.Column('moeda', sa.Enum('BRL', 'USD', 'EUR', name='moeda_enum'), nullable=False),
    sa.Column('saldo_atual', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'INATIVA', name='status_conta_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('variacao_dia', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('fonte', sa.Enum('BRAPI', 'YFINANCE', 'MANUAL', name='fonte_cotacao_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saldos_contas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('DEPOSITO', 'SAQUE', 'TRANSFERENCIA', 'PIX', 'TED', 'AJUSTE', name='tipo_saldo_conta_enum'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('data_operacao', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldos_contas')
    op.drop_table('cotacoes')
    op.drop_table('contas')
    op.drop_table('usuarios')
    op.drop_table('instituicoes')
    op.drop_table('ativos')
    # ### end Alembic commands ###
