"""Adiciona ir_retido e data_ex ao modelo Provento

Revision ID: 0e4c3c2e5c91
Revises: c1a2b3d4e5f6
Create Date: 2026-06-28 11:53:40.309424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4c3c2e5c91'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proventos', sa.Column('data_ex', sa.Date(), nullable=True))
    op.add_column('proventos', sa.Column('ir_retido', sa.Numeric(precision=20, scale=8), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proventos', 'ir_retido')
    op.drop_column('proventos', 'data_ex')
    # ### end Alembic commands ###
