"""Initial commit

Revision ID: 56ff477d7396
Revises: 
Create Date: 2026-06-21 10:22:20.139356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ff477d7396'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('classe', sa.Enum('ACAO', 'FII', 'ETF', 'BDR', 'CRIPTOMOEDA', 'REIT', 'STOCK', 'TESOURO_DIRETO', 'CDB', 'LCI', 'LCA', 'DEBENTURE', 'CRI', 'CRA', 'FUNDO_INVESTIMENTO', 'OPCAO', 'OUTRO', name='classe_ativo_enum'), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('segmento_fii', sa.Enum('TIJOLO', 'PAPEL', 'LOGISTICO', 'SHOPPING', 'LAJES_CORPORATIVAS', 'HIBRIDO', 'RECEBIVEL', 'FUNDO_DE_FUNDOS', 'OUTRO', name='segmento_fii_enum'), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('regiao', sa.Enum('BRASIL', 'AMERICA_NORTE', 'EUROPA', 'ASIA', 'OUTRO', name='regiao_enum'), nullable=False),
    sa.Column('moeda', sa.Enum('BRL', 'USD', 'EUR', name='moeda_ativo_enum'), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status_ativo_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ativos_ticker'), 'ativos', ['ticker'], unique=True)
    op.create_table('instituicoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('BANCO', 'CORRETORA', 'OUTRO', name='tipo_instituicao_enum'), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'INATIVA', name='status_instituicao_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carteiras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.Enum('REAL', 'TESTE', 'SIMULADA', 'ESTRATEGIA', name='tipo_carteira_enum'), nullable=False),
    sa.Column('objetivo', sa.Enum('DIVIDENDOS', 'CRESCIMENTO', 'APOSENTADORIA', 'INTERNACIONAL', 'CRIPTO', 'LIVRE', 'RENDA_PASSIVA', 'RESERVA_EMERGENCIA', 'OUTRO', name='objetivo_carteira_enum'), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('saldo_atual', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('saldo_atual >= 0', name='ck_carteiras_saldo_atual_nonneg'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carteiras_usuario_id'), 'carteiras', ['usuario_id'], unique=False)
    op.create_table('contas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instituicao_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('CORRENTE', 'POUPANCA', 'INVESTIMENTO', 'PAGAMENTO', 'OUTRO', name='tipo_conta_enum'), nullable=False),
    sa.Column('moeda', sa.Enum('BRL', 'USD', 'EUR', name='moeda_enum'), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('saldo_atual', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('data_abertura', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'INATIVA', name='status_conta_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('saldo_atual >= 0', name='ck_contas_saldo_atual_nonneg'),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_instituicao_id'), 'contas', ['instituicao_id'], unique=False)
    op.create_table('cotacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotacoes_ativo_id'), 'cotacoes', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_cotacoes_data'), 'cotacoes', ['data'], unique=False)
    op.create_table('eventos_corporativos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('SPLIT', 'GRUPAMENTO', 'BONIFICACAO', 'SUBSCRICAO', 'AMORTIZACAO', 'INCORPORACAO', 'FUSAO', 'CISAO', 'OUTRO', name='tipo_evento_corporativo_enum'), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('fator', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('valor', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ativo_destino_id', sa.UUID(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('processado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ativo_destino_id'], ['ativos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_corporativos_ativo_destino_id'), 'eventos_corporativos', ['ativo_destino_id'], unique=False)
    op.create_index(op.f('ix_eventos_corporativos_ativo_id'), 'eventos_corporativos', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_eventos_corporativos_data_evento'), 'eventos_corporativos', ['data_evento'], unique=False)
    op.create_index(op.f('ix_eventos_corporativos_tipo'), 'eventos_corporativos', ['tipo'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carteira_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('COMPRA', 'VENDA', name='tipo_movimentacao_enum'), nullable=False),
    sa.Column('tipo_operacao', sa.Enum('SWING', 'DAY_TRADE', 'POSITION', name='tipo_operacao_enum'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('preco', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('custos', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('data_movimentacao', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_ativo_id'), 'movimentacoes', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_carteira_id'), 'movimentacoes', ['carteira_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_conta_id'), 'movimentacoes', ['conta_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_data_movimentacao'), 'movimentacoes', ['data_movimentacao'], unique=False)
    op.create_index(op.f('ix_movimentacoes_tipo'), 'movimentacoes', ['tipo'], unique=False)
    op.create_table('posicoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carteira_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('preco_medio', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantidade >= 0', name='ck_posicoes_quantidade_nonneg'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posicoes_ativo_id'), 'posicoes', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_posicoes_carteira_id'), 'posicoes', ['carteira_id'], unique=False)
    op.create_index(op.f('ix_posicoes_conta_id'), 'posicoes', ['conta_id'], unique=False)
    op.create_table('proventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carteira_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('ativo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('DIVIDENDO', 'JCP', 'RENDIMENTO', 'AMORTIZACAO', 'OUTRO', name='tipo_provento_enum'), nullable=False),
    sa.Column('data_com', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reinvestido', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proventos_ativo_id'), 'proventos', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_proventos_carteira_id'), 'proventos', ['carteira_id'], unique=False)
    op.create_index(op.f('ix_proventos_conta_id'), 'proventos', ['conta_id'], unique=False)
    op.create_index(op.f('ix_proventos_tipo'), 'proventos', ['tipo'], unique=False)
    op.create_table('saldos_contas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('DEPOSITO', 'SAQUE', 'TRANSFERENCIA', 'PIX', 'TED', 'AJUSTE', name='tipo_saldo_conta_enum'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('data_operacao', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saldos_contas_conta_id'), 'saldos_contas', ['conta_id'], unique=False)
    op.create_table('aportes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carteira_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('EXTERNO', 'REINVESTIMENTO', name='tipo_aporte_enum'), nullable=False),
    sa.Column('origem', sa.Enum('DIVIDENDO', 'JCP', 'RENDIMENTO', 'JUROS_RF', 'GANHO_CAPITAL', 'OUTRO', name='origem_aporte_enum'), nullable=True),
    sa.Column('valor', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('data_aporte', sa.Date(), nullable=False),
    sa.Column('movimentacao_id', sa.UUID(), nullable=True),
    sa.Column('provento_id', sa.UUID(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteiras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provento_id'], ['proventos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aportes_carteira_id'), 'aportes', ['carteira_id'], unique=False)
    op.create_index(op.f('ix_aportes_conta_id'), 'aportes', ['conta_id'], unique=False)
    op.create_index(op.f('ix_aportes_data_aporte'), 'aportes', ['data_aporte'], unique=False)
    op.create_index(op.f('ix_aportes_movimentacao_id'), 'aportes', ['movimentacao_id'], unique=False)
    op.create_index(op.f('ix_aportes_provento_id'), 'aportes', ['provento_id'], unique=False)
    op.create_index(op.f('ix_aportes_tipo'), 'aportes', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aportes_tipo'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_provento_id'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_movimentacao_id'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_data_aporte'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_conta_id'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_carteira_id'), table_name='aportes')
    op.drop_table('aportes')
    op.drop_index(op.f('ix_saldos_contas_conta_id'), table_name='saldos_contas')
    op.drop_table('saldos_contas')
    op.drop_index(op.f('ix_proventos_tipo'), table_name='proventos')
    op.drop_index(op.f('ix_proventos_conta_id'), table_name='proventos')
    op.drop_index(op.f('ix_proventos_carteira_id'), table_name='proventos')
    op.drop_index(op.f('ix_proventos_ativo_id'), table_name='proventos')
    op.drop_table('proventos')
    op.drop_index(op.f('ix_posicoes_conta_id'), table_name='posicoes')
    op.drop_index(op.f('ix_posicoes_carteira_id'), table_name='posicoes')
    op.drop_index(op.f('ix_posicoes_ativo_id'), table_name='posicoes')
    op.drop_table('posicoes')
    op.drop_index(op.f('ix_movimentacoes_tipo'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_data_movimentacao'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_conta_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_carteira_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_ativo_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_eventos_corporativos_tipo'), table_name='eventos_corporativos')
    op.drop_index(op.f('ix_eventos_corporativos_data_evento'), table_name='eventos_corporativos')
    op.drop_index(op.f('ix_eventos_corporativos_ativo_id'), table_name='eventos_corporativos')
    op.drop_index(op.f('ix_eventos_corporativos_ativo_destino_id'), table_name='eventos_corporativos')
    op.drop_table('eventos_corporativos')
    op.drop_index(op.f('ix_cotacoes_data'), table_name='cotacoes')
    op.drop_index(op.f('ix_cotacoes_ativo_id'), table_name='cotacoes')
    op.drop_table('cotacoes')
    op.drop_index(op.f('ix_contas_instituicao_id'), table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_carteiras_usuario_id'), table_name='carteiras')
    op.drop_table('carteiras')
    op.drop_table('usuarios')
    op.drop_table('instituicoes')
    op.drop_index(op.f('ix_ativos_ticker'), table_name='ativos')
    op.drop_table('ativos')
    # ### end Alembic commands ###
