# FILE: backend/migrations/versions/7acfddb0475a_adiciona_quantidade_na_data_e_.py
"""Adiciona quantidade_na_data e observacoes ao modelo Provento

Revision ID: 7acfddb0475a
Revises: 0e4c3c2e5c91
Create Date: 2026-06-28 15:04:00.000000

"""
from typing import Sequence, Union, Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7acfddb0475a'
down_revision: Union[str, Sequence[str], None] = '0e4c3c2e5c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proventos', sa.Column('quantidade_na_data', sa.Numeric(precision=20, scale=8), nullable=True, server_default='0.00'))
    # op.add_column('proventos', sa.Column('observacoes', sa.Text(), nullable=True)) # Comentado: Coluna 'observacoes' já existe ou será adicionada em outra migração

    # Removendo índices e constraints existentes antes de recriá-los com nomes explícitos
    # É importante que os nomes aqui correspondam aos nomes que o Alembic gerou ou que você definiu anteriormente.
    # Se você não tem certeza dos nomes, pode inspecionar o banco de dados ou o histórico de migrações.
    # Para este exemplo, estou usando os nomes que apareceram em tracebacks anteriores ou são comuns.
    op.drop_index('ix_proventos_ativo_id', table_name='proventos', if_exists=True)
    op.drop_index('ix_proventos_carteira_id', table_name='proventos', if_exists=True)
    op.drop_index('ix_proventos_conta_id', table_name='proventos', if_exists=True)
    op.drop_index('ix_proventos_tipo', table_name='proventos', if_exists=True)

    # Removendo chaves estrangeiras existentes com nomes conhecidos
    op.drop_constraint('proventos_conta_id_fkey', 'proventos', type_='foreignkey', if_exists=True)
    op.drop_constraint('proventos_carteira_id_fkey', 'proventos', type_='foreignkey', if_exists=True)
    op.drop_constraint('proventos_ativo_id_fkey', 'proventos', type_='foreignkey', if_exists=True)
    # Se houver outras chaves estrangeiras com nomes gerados automaticamente (ex: fk_proventos_ativo_id),
    # você precisaria descobrir esses nomes e adicioná-los aqui com if_exists=True.
    # Por enquanto, vamos focar nos nomes que já apareceram.

    # Recriando chaves estrangeiras com nomes explícitos
    op.create_foreign_key('proventos_ativo_id_fkey', 'proventos', 'ativos', ['ativo_id'], ['id'])
    op.create_foreign_key('proventos_carteira_id_fkey', 'proventos', 'carteiras', ['carteira_id'], ['id'])
    # A chave estrangeira para 'conta_id' será adicionada na próxima migração (05627d7718c5)

    # Removendo colunas 'quantidade' e 'conta_id' que serão tratadas em outras migrações ou já foram
    op.drop_column('proventos', 'quantidade', if_exists=True)
    op.drop_column('proventos', 'conta_id', if_exists=True) # Esta coluna será adicionada na próxima migração

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Recriando colunas 'quantidade' e 'conta_id' que foram removidas no upgrade
    op.add_column('proventos', sa.Column('conta_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('proventos', sa.Column('quantidade', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False, server_default='0.00')) # Adicionado server_default

    # Removendo as chaves estrangeiras criadas no upgrade
    op.drop_constraint('proventos_ativo_id_fkey', 'proventos', type_='foreignkey', if_exists=True)
    op.drop_constraint('proventos_carteira_id_fkey', 'proventos', type_='foreignkey', if_exists=True)
    # A chave estrangeira para 'conta_id' não foi criada nesta migração no upgrade, então não a removemos aqui.

    # Recriando as chaves estrangeiras originais (se foram removidas no upgrade)
    # Estes nomes devem corresponder aos nomes que existiam antes desta migração.
    op.create_foreign_key('proventos_ativo_id_fkey', 'proventos', 'ativos', ['ativo_id'], ['id'])
    op.create_foreign_key('proventos_carteira_id_fkey', 'proventos', 'carteiras', ['carteira_id'], ['id'])
    op.create_foreign_key('proventos_conta_id_fkey', 'proventos', 'contas', ['conta_id'], ['id']) # Recria a FK original de conta_id

    # Recriando índices que foram removidos no upgrade
    op.create_index('ix_proventos_tipo', 'proventos', ['tipo'], unique=False, if_exists=True)
    op.create_index('ix_proventos_conta_id', 'proventos', ['conta_id'], unique=False, if_exists=True)
    op.create_index('ix_proventos_carteira_id', 'proventos', ['carteira_id'], unique=False, if_exists=True)
    op.create_index('ix_proventos_ativo_id', 'proventos', ['ativo_id'], unique=False, if_exists=True)

    # Removendo colunas adicionadas no upgrade
    # op.drop_column('proventos', 'observacoes', if_exists=True) # Comentado: Se não foi adicionada no upgrade, não deve ser removida aqui.
    op.drop_column('proventos', 'quantidade_na_data', if_exists=True)
    # ### end Alembic commands ###