"""Adiciona usuario padrao

Revision ID: ba8bf0c084a9
Revises: 9ba35ec4707e
Create Date: 2026-06-25 11:38:04.505834

"""
from typing import Sequence, Union
import uuid
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8bf0c084a9'
down_revision: Union[str, Sequence[str], None] = '9ba35ec4707e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Inserir um usuário padrão
    # Usamos o mesmo ID que causou o erro de ForeignKeyViolation para consistência
    # Em um ambiente real, a senha_hash deveria ser gerada de forma segura.
    # Aqui, é um placeholder.
    op.execute(
        sa.text(
            """
            INSERT INTO usuarios (id, nome, email, senha_hash, created_at, updated_at)
            VALUES (
                '3e509155-922a-4f24-a810-488dc637c841',
                'Usuario Padrao',
                'usuario.padrao@example.com',
                'hash_da_senha_padrao',
                NOW(),
                NOW()
            )
            ON CONFLICT (id) DO NOTHING;
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover o usuário padrão
    op.execute(
        sa.text(
            """
            DELETE FROM usuarios
            WHERE id = '3e509155-922a-4f24-a810-488dc637c841';
            """
        )
    )
    # ### end Alembic commands ###